async (page) => {
  const check = (condition, message) => { if (!condition) throw new Error(message); };
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 3840, height: 2160 });
  await page.goto('http://127.0.0.1:5173/');
  await page.locator('#loading').waitFor({ state: 'hidden' });
  await page.locator('#community-more').evaluate(element => { element.open = true; });
  check(await page.locator('#walking-hud').isVisible(), 'District should start on foot');
  await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.multiplayer==='joined' && document.querySelector('#community-local').options.length>0);
  const toggle = page.locator('#panel-toggle');
  // The rail sidebar shows one section at a time; select the tab a control lives in first.
  const rail = section => page.locator(`[data-section=${section}]`).click();
  const voices = async () => { await rail('settings-section'); await page.locator('details.rail-disclosure', { hasText: 'Voices' }).evaluate(details => { details.open = true; }); };
  if (await toggle.getAttribute('aria-expanded') === 'false') await toggle.click();
  check(await page.locator('#destination option').count() === 30, 'Expected current mapped directory destinations');
  await rail('settings-section');
  await page.locator('button[data-theme-preference=dark]').click();
  check(await page.locator('html').getAttribute('data-theme') === 'dark', 'Dark appearance must apply');
  await page.locator('#panel-toggle').click();
  await page.waitForTimeout(400);
  check(await page.locator('#canvas-host').evaluate(el => el === document.activeElement), 'Walking focus must recover after collapse');
  const start = JSON.parse(await page.locator('#walking-hud').getAttribute('data-position'));
  await page.keyboard.down('KeyW'); await page.waitForTimeout(1200); await page.keyboard.up('KeyW');
  const moved = JSON.parse(await page.locator('#walking-hud').getAttribute('data-position'));
  check(Math.hypot(moved[0]-start[0], moved[2]-start[2]) > 0.7, 'W must move the camera through the district');
  const uhd = await page.locator('canvas').evaluate(el => [el.width, el.height]);
  check(uhd[0] === 3840 && uhd[1] === 2160, 'Collapsed buffer must be native UHD');
  await page.screenshot({ path: 'output/playwright/district-walking-4k.png' });
  await toggle.click();
  await rail('explore-section');
  await page.locator('#destination').selectOption({ label: 'Hermès' });
  await page.locator('#visit-destination').click();
  check(await page.locator('#walking-hud').isVisible(), 'Store arrival must preserve walking');
  await rail('community-section');
  await page.locator('#community-local').selectOption('store-osm-node-8172494969-person-2');
  await page.waitForTimeout(1100);await page.locator('#community-meet').click();
  await page.locator('#community-dialogue').waitFor({state:'visible'});
  await page.locator('#community-about').click();
  await page.waitForFunction(() => !document.querySelector('#community-attribution').textContent.includes('checking'));
  check((await page.locator('#community-speech').textContent()).length > 40, 'Conversation must respond');
  check((await page.locator('#community-attribution').textContent()).includes('Authored dialogue'), 'Authored conversation must be attributed honestly');
  await page.locator('#community-close').click();
  await page.waitForTimeout(1100);await page.keyboard.press('KeyE');
  await page.locator('#community-dialogue').waitFor({state:'visible'});
  check(await page.locator('#community-dialogue').isVisible(), 'E must reopen a nearby local encounter');
  await page.locator('#community-close').click();

  // Shared arrival is asynchronous: the dialogue confirms authoritative travel.
  await rail('community-section');
  check(await page.locator('#community-reset').count()===0,'Solo reset control is absent');
  await page.waitForFunction(()=>!document.querySelector('#community-run').disabled);
  await toggle.click();
  await page.waitForTimeout(400);
  await page.screenshot({ path: 'output/playwright/district-community-4k.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForTimeout(400);
  check(!await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), 'Mobile must not overflow horizontally');
  check(await page.locator('#walking-hud').isVisible(), 'Mobile must retain walking');
  await page.screenshot({ path: 'output/playwright/district-mobile.png' });
  await toggle.click();
  check(await page.locator('#scene-select').count() === 0, 'Only the district should be offered');
  await rail('settings-section');
  await page.locator('#reload').click();
  await page.locator('#loading').waitFor({ state: 'hidden' });
  await page.setViewportSize({ width: 1920, height: 1080 });
  check(await page.locator('#walking-hud').isVisible(), 'Reloading the district resumes walking');
  await page.waitForTimeout(1200);
  check(page.workers().filter(worker=>worker.url().includes('/navigation-worker')).length===0,'Reloading the shared district must not start a solo route worker');
  check(errors.length === 0, `Browser errors: ${errors.join('; ')}`);
  return { uhd, movedMeters: Math.hypot(moved[0]-start[0], moved[2]-start[2]), destinations:30, nearbyConversation:true,  mobileNoOverflow:true, sceneSwitch:true, routeWorkerLifecycle:true, browserErrors:errors };
}
