async page => {
  const checks=[],errors=[];
  const check=(condition,label)=>{if(!condition)throw new Error(label);checks.push(label);};
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto('http://127.0.0.1:5181/?motion-debug=1');
  await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.playerReady==='true');
  await page.waitForFunction(()=>document.querySelector('.asset-progress').hidden);
  check(await page.locator('.player-settings').evaluate(el=>!el.open),'Secondary character controls start closed');
  check(await page.locator('#player-flight').isVisible(),'Flight is available without opening settings');
  check(await page.locator('#player-companion').isVisible(),'Jev is available without opening settings');
  check(await page.locator('.invasion-controls').evaluate(el=>el.tagName==='DETAILS'&&!el.open),'Optional scenario starts collapsed');
  await page.locator('.player-settings summary').click();
  check(await page.locator('#player-vehicle').isVisible(),'Rides can be discovered from the character card');
  await page.locator('#player-camera').focus();await page.keyboard.press('h');
  check(await page.locator('.clear-view-toggle').evaluate(el=>el===document.activeElement),'Clear view moves focus out of hidden controls');
  await page.keyboard.press('h');await page.locator('.player-settings summary').click();
  await page.locator('#panel-toggle').click();
  await page.locator('[data-section=settings-section]').focus();await page.keyboard.press('Escape');
  check(await page.locator('#panel-toggle').getAttribute('aria-expanded')==='false','Escape closes the exploration panel');
  check(await page.locator('#panel-toggle').evaluate(el=>el===document.activeElement),'Closing the panel restores trigger focus');
  await page.screenshot({path:'output/playwright/aaa-hud-desktop.png'});
  await page.setViewportSize({width:390,height:844});
  // The media-query change that collapses the dock is delivered after the resize, not during it.
  check(await page.waitForFunction(()=>!document.querySelector('.visit-tools').open,null,{timeout:2000}).then(()=>true,()=>false),'Small windows start with a compact play dock');
  await page.locator('.visit-tools-toggle').click();
  check(await page.locator('#player-flight').isVisible(),'Small-window play dock opens');
  await page.locator('#player-flight').focus();await page.keyboard.press('Escape');
  check(await page.locator('.visit-tools').evaluate(el=>!el.open),'Escape closes the play dock');
  check(await page.locator('.visit-tools-toggle').evaluate(el=>el===document.activeElement),'Escape restores dock focus');
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal overflow');
  await page.screenshot({path:'output/playwright/aaa-hud-mobile.png'});
  // CSS must honor the runtime's shared-mode hidden flag.
  await page.locator('.visit-tools-toggle').click();
  await page.locator('#player-companion').evaluate(el=>el.hidden=true);
  check(!await page.locator('#player-companion').isVisible(),'Shared mode hides the unavailable companion action');
  await page.locator('#player-companion').evaluate(el=>el.hidden=false);
  await page.setViewportSize({width:667,height:375});
  if(await page.locator('.visit-tools').evaluate(el=>el.open))await page.locator('.visit-tools-toggle').click();
  await page.locator('#walking-controls-toggle').click();
  await page.locator('.visit-tools-toggle').click();
  check(await page.locator('.visit-tools-content').evaluate(el=>el.clientHeight>=140),'Short landscape windows retain a usable scrolling dock');
  await page.locator('.invasion-controls > summary').click();
  await page.locator('#invasion-toggle').scrollIntoViewIfNeeded();
  check(await page.locator('#invasion-toggle').evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;}),'The last disclosure action can be reached in landscape');
  check(await page.locator('.visit-tools-toggle').evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.right-12,r.top+r.height/2));}),'The dock collapse indicator is not covered by Clear view');
  check(await page.locator('.clear-view-toggle').evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.left+r.width/2,r.top+r.height/2));}),'Clear view remains independently reachable in landscape');
  await page.screenshot({path:'output/playwright/aaa-hud-landscape.png'});
  await page.setViewportSize({width:1440,height:1000});
  await page.route('**/v1/auto',route=>{const packet=route.request().postDataJSON();return route.fulfill({json:{schema_version:1,tick:packet.tick,generation:packet.generation,source:'unavailable',reason:'not_configured',candidate_id:'wait',confidence:0}});});
  await page.locator('#auto-toggle').click();
  await page.waitForFunction(()=>document.querySelector('#auto-status').textContent.includes('Connect Jev in Settings'));
  check(await page.locator('#auto-status').isVisible(),'Unavailable guided visits explain how to connect Jev');
  await page.locator('#auto-toggle').click();await page.unroute('**/v1/auto');
  // Conversation stays clear of the play dock in a compact desktop window.
  await page.setViewportSize({width:960,height:640});
  await page.locator('#walking-talk').click();
  await page.locator('#community-dialogue').waitFor({state:'visible'});
  await page.locator('.visit-tools').waitFor({state:'hidden'});
  check(!await page.locator('.visit-tools').isVisible(),'Conversation clears competing controls in compact windows');
  await page.locator('#community-close').focus();await page.keyboard.press('Escape');
  check(await page.locator('#canvas-host').evaluate(el=>el===document.activeElement),'Conversation Escape returns focus to the world');
  await page.locator('.visit-tools').waitFor({state:'visible'});
  check(await page.locator('.visit-tools').isVisible(),'Play controls return after conversation');
  await page.emulateMedia({reducedMotion:'reduce'});
  check(await page.locator('.visit-tools-toggle').evaluate(el=>getComputedStyle(el).transitionDuration==='0s'),'Reduced motion removes dock transitions');
  await page.evaluate(()=>document.documentElement.dataset.theme='dark');
  await page.screenshot({path:'output/playwright/aaa-hud-dark.png'});
  check(!errors.length,`No page errors: ${errors.join('; ')}`);
  return {checks,errors};
}
