async page=>{
  const checks=[],errors=[];page.on('pageerror',error=>errors.push(error.message));
  page.on('console',message=>{if(message.type()==='error'&&/Shader Error|VALIDATE_STATUS|WebGLProgram/.test(message.text()))errors.push(message.text());});
  const check=(ok,message)=>{if(!ok)throw new Error(message);checks.push(message);};
  const read=()=>page.evaluate(()=>window.__riverForce());
  const meet=async id=>{
    if(await page.locator('#community-dialogue').isVisible())await page.locator('#community-close').click();
    if(await page.locator('#panel-toggle').getAttribute('aria-expanded')==='false')await page.locator('#panel-toggle').click();
    await page.locator('[data-section=community-section]').click();
    if(!await page.locator('#community-more').evaluate(e=>e.open))await page.locator('#community-more > summary').click();
    await page.locator('#community-local').selectOption(id);await page.locator('#community-meet').click();
    await page.locator('#community-dialogue').waitFor({state:'visible'});
    await page.waitForTimeout(300);await page.locator('#community-close').click();await page.locator('#panel-toggle').click();
    await page.waitForTimeout(300);
  };
  const lift=async id=>{
    await page.waitForFunction(id=>[...document.querySelector('#force-target').options].some(o=>o.value===id),id);
    await page.locator('#force-target').selectOption(id);await page.locator('#force-lift').click();
    await page.waitForFunction(()=>window.__riverForce().active?.mode==='lift');
  };
  const lower=async()=>{await page.locator('#canvas-host').focus();await page.keyboard.press('KeyX');await page.waitForFunction(()=>!window.__riverForce().active,null,{timeout:12000});};
  await page.setViewportSize({width:1440,height:1000});await page.emulateMedia({reducedMotion:'no-preference'});
  await page.goto('http://127.0.0.1:5181/?motion-debug=1');
  await page.waitForFunction(()=>{const d=document.querySelector('#canvas-host').dataset;return d.charactersReady==='24'&&d.playerReady==='true'&&d.storePeopleReady===d.storePeopleTotal;},null,{timeout:90000});
  await meet('local-00');await page.locator('#canvas-host').focus();await page.keyboard.press('KeyT');
  check((await read()).enabled,'T enables Force mode');
  const point=await page.evaluate(()=>window.__riverPeople('spine_03').find(p=>p.id==='local-00').screen);
  await page.mouse.click(...point);
  check(await page.locator('#force-target').inputValue()==='local-00','A real pointer click targets the person in Force mode');
  check(!await page.locator('#community-dialogue').isVisible(),'Force picking does not open a conversation');
  const initial=(await read()).targets.find(t=>t.id==='local-00');
  await page.locator('#canvas-host').focus();await page.keyboard.press('KeyG');
  const acquired=(await read()).active;
  check(acquired?.id==='local-00','G acquires the selected person');
  await page.waitForFunction(y=>window.__riverForce().active?.position[1]>y+1,initial.position[1]);
  const held=await read(),person=held.targets.find(t=>t.id==='local-00');
  check(person.renderedPosition[1]-initial.renderedPosition[1]>1,'The rendered person rises, not just the state');
  check(Math.hypot(person.position[0]-acquired.position[0],person.position[2]-acquired.position[2])<.001,'Force hold suspends pedestrian navigation');
  const personFX=await page.evaluate(()=>window.__riverLiftSparkles());
  check(personFX.wand>0&&personFX.target>0,'Wand and person both emit lift sparkles');
  await page.screenshot({path:'output/playwright/force-person-held.png'});
  await lower();check(!(await read()).active,'X gently lands and releases the person');
  await page.waitForFunction(()=>window.__riverLiftSparkles().count===0);
  check(true,'Sparkles finish fading after landing');
  await page.waitForFunction(()=>JSON.parse(document.querySelector('#community-life-status').dataset.residents).find(p=>p.id==='local-00').speed>.1,null,{timeout:20000});
  check(true,'Released person resumes walking');
  await lift('local-00');await page.waitForTimeout(1800);
  const beforePush=(await read()).active.position;
  await page.locator('#force-push').click();await page.waitForFunction(()=>!window.__riverForce().active,null,{timeout:12000});
  const pushed=(await read()).targets.find(t=>t.id==='local-00').position;
  check(Math.hypot(pushed[0]-beforePush[0],pushed[2]-beforePush[2])>.15,'A Force push displaces a person and lands them');

  const candidates=await page.evaluate(()=>{
    const targets=window.__riverForce().targets,bins=targets.filter(t=>t.kind==='object');
    return targets.filter(t=>t.id.startsWith('local-')).map(p=>({id:p.id,distance:Math.min(...bins.map(b=>Math.hypot(p.position[0]-b.position[0],p.position[2]-b.position[2])))})).sort((a,b)=>a.distance-b.distance).slice(0,5);
  });
  let bin;
  for(const candidate of candidates){await meet(candidate.id);bin=(await read()).targets.find(t=>t.kind==='object'&&t.eligible);if(bin)break;}
  check(Boolean(bin),'An existing street bin can be targeted through normal travel');
  await lift(bin.id);await page.waitForFunction(y=>window.__riverForce().active?.position[1]>y+1,bin.position[1]);
  const raised=(await read()).targets.find(t=>t.id===bin.id);
  check(raised.renderedPosition[1]-bin.renderedPosition[1]>1,'The complete bin rises with its lid');
  check(await page.evaluate(()=>document.activeElement.id==='canvas-host'),'Pointer spell controls return focus to walking');
  const carryStart=await page.evaluate(()=>({body:window.__riverForce().active,pose:window.__riverCarriage().pose}));
  await page.keyboard.down('KeyS');await page.waitForTimeout(1400);await page.keyboard.up('KeyS');
  await page.waitForTimeout(1200);
  const carryEnd=await page.evaluate(()=>({body:window.__riverForce().active,pose:window.__riverCarriage().pose,yaw:window.__riverCarriage().riderYaw,fx:window.__riverLiftSparkles()}));
  check(carryEnd.body?.mode==='lift','Walking preserves the active lift');
  check(Math.hypot(carryEnd.pose.position[0]-carryStart.pose.position[0],carryEnd.pose.position[2]-carryStart.pose.position[2])>.4,'Jevica walks while holding a target');
  check(Math.hypot(carryEnd.body.position[0]-carryStart.body.position[0],carryEnd.body.position[2]-carryStart.body.position[2])>.25,'The lifted bin follows her movement');
  check(carryEnd.fx.wand>0&&carryEnd.fx.target>0&&carryEnd.fx.count<=256,'Both sparkle emitters remain active within the pool budget while carrying');
  const facing=Math.atan2(carryEnd.body.position[0]-carryEnd.pose.position[0],carryEnd.body.position[2]-carryEnd.pose.position[2])-carryEnd.yaw;
  check(Math.abs(Math.atan2(Math.sin(facing),Math.cos(facing)))<.08,'Jevica keeps facing the carried object after backpedalling');
  await page.screenshot({path:'output/playwright/force-bin-held.png'});
  await page.locator('#canvas-host').focus();await page.keyboard.press('KeyR');
  await page.waitForFunction(()=>!window.__riverForce().active,null,{timeout:12000});
  const landed=(await read()).targets.find(t=>t.id===bin.id);
  check(Math.hypot(landed.position[0]-raised.position[0],landed.position[2]-raised.position[2])>.2,'R pushes a real object and it settles at its new position');

  const staff=await page.evaluate(()=>window.__riverPeople().find(p=>p.role==='staff').id);await meet(staff);
  const station=(await read()).targets.find(t=>t.id===staff);await lift(staff);
  await page.waitForFunction(y=>window.__riverForce().active?.position[1]>y+.5,station.position[1]);
  check(await page.locator('#force-push').isDisabled(),'Indoor stations lift in place without crossing work surfaces');
  const workBefore=await page.evaluate(id=>window.__riverPeople().find(p=>p.id===id).workTime,staff);
  await page.waitForTimeout(400);
  const workAfter=await page.evaluate(id=>window.__riverPeople().find(p=>p.id===id).workTime,staff);
  check(workBefore===workAfter,'A levitated worker pauses their task');
  await page.screenshot({path:'output/playwright/force-worker-held.png'});
  await page.locator('#canvas-host').focus();await page.keyboard.press('Escape');
  await page.waitForFunction(()=>!window.__riverForce().active,null,{timeout:12000});
  await page.waitForFunction(({id,before})=>window.__riverPeople().find(p=>p.id===id).workTime>before,{id:staff,before:workBefore},{timeout:10000});
  check(true,'Escape lowers the worker and their task resumes');
  await page.locator('#force-toggle').click();check(!(await read()).enabled,'Force mode can be disabled');
  check(!errors.length,'No uncaught browser errors');
  return {checks,person:{initial,held:person},bin:{initial:bin,raised,landed},carry:{start:carryStart,end:carryEnd},personFX,staff,errors};
}
