async page => {
  const checks = [];
  const check = (value, message) => { if (!value) throw new Error(message); checks.push(message); };
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto('http://127.0.0.1:5173/');
  await page.locator('#loading').waitFor({ state: 'hidden' });
  await page.waitForFunction(() => document.querySelector('#canvas-host').dataset.playerReady === 'true');
  check(await page.locator('#settings-toggle').count() === 1, 'Settings has a dedicated launcher');
  await page.locator('#settings-toggle').click();
  check(await page.locator('#settings-dialog').evaluate(node => node.open), 'Settings opens as a native modal');
  await page.getByRole('tab', { name: 'Graphics', exact: true }).click();
  await page.locator('[data-quality=smooth]').click();
  check(await page.locator('[data-quality=smooth]').getAttribute('aria-pressed') === 'true', 'Existing graphics control works in its own settings tab');
  await page.getByRole('tab', { name: 'Graphics', exact: true }).focus();
  await page.keyboard.press('ArrowDown');
  check(await page.getByRole('tab', { name: 'Audio', exact: true }).getAttribute('aria-selected') === 'true', 'Sidebar tabs support arrow navigation');
  await page.keyboard.press('Escape');
  check(await page.locator('#settings-toggle').evaluate(node => node === document.activeElement), 'Escape restores settings launcher focus');
  await page.locator('#panel-toggle').click();
  await page.locator('#people-toggle').click();
  check(await page.locator('#explore-section').isVisible() && await page.locator('#community-section').isVisible(), 'People and Places can be open together on desktop');
  const places = await page.locator('#explore-section').boundingBox(), people = await page.locator('#community-section').boundingBox();
  check(places.x + places.width < people.x, 'People and Places occupy opposite edges');
  const chat = await page.locator('.town-chat-dock').boundingBox();
  check(places.y + places.height < chat.y, 'Expanded Places leaves room for chat');
  await page.screenshot({ path: 'output/playwright/game-hud-panels.png' });
  await page.setViewportSize({ width: 1024, height: 900 });
  const compactChat = await page.locator('.town-chat-dock').boundingBox();
  const movement = await page.locator('.walking-console').boundingBox();
  check(movement.x >= compactChat.x + compactChat.width, 'Movement controls do not overlap chat on smaller desktops');
  await page.setViewportSize({ width: 850, height: 900 });
  check(await page.locator('#community-section').isVisible() && !(await page.locator('#explore-section').isVisible()), 'Narrowing the window retains the most recently opened panel');
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.locator('#panel-toggle').click();
  await page.locator('#panel-toggle').click();
  check(await page.locator('#control-panel').evaluate(node => getComputedStyle(node).opacity === '1'), 'People stays opaque when Places closes');
  await page.screenshot({ path: 'output/playwright/game-hud-people.png' });
  await page.locator('#people-toggle').click();
  const input = page.getByRole('textbox', { name: 'Message the town', exact: true });
  await input.fill('A draft for the district');
  await page.locator('.town-chat-toggle').click();
  await page.locator('.town-chat-toggle').click();
  check(await input.inputValue() === 'A draft for the district', 'Collapsing chat preserves the draft');
  await input.fill('Hello from the new chat dock');
  await input.press('Enter');
  await page.locator('.multiplayer-chat-message').filter({ hasText: 'Hello from the new chat dock' }).waitFor();
  check(await input.inputValue() === '', 'Confirmed town message clears the composer');
  await page.screenshot({ path: 'output/playwright/game-hud-desktop.png' });
  await page.locator('#settings-toggle').click();
  await page.screenshot({ path: 'output/playwright/game-hud-settings.png' });
  await page.keyboard.press('Escape');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('#panel-toggle').click();
  await page.locator('#people-toggle').click();
  check(!(await page.locator('#explore-section').isVisible()), 'Narrow screens show only one expanded side panel');
  await page.locator('#settings-toggle').click();
  const dialog = await page.locator('#settings-dialog').boundingBox();
  check(dialog.x >= 0 && dialog.x + dialog.width <= 390, 'Settings fits a narrow screen');
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'HUD does not create horizontal overflow');
  await page.screenshot({ path: 'output/playwright/game-hud-mobile.png' });
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Close People', exact: true }).focus();
  await page.keyboard.press('KeyH');
  check(await page.locator('.commands-toggle').evaluate(node => node.checkVisibility({ visibilityProperty: true }) && node === document.activeElement), 'Mobile Clear view exposes and focuses its restore control');
  await page.keyboard.press('KeyH');
  check(await page.locator('#canvas-host').evaluate(node => node === document.activeElement), 'Restoring mobile panels keeps focus on a visible control');
  await page.locator('#people-toggle').click();
  if (await page.locator('.town-chat-dock').evaluate(node => node.open)) await page.locator('.town-chat-toggle').click();
  const commands = await page.locator('.commands-toggle').boundingBox();
  const walking = await page.locator('.walking-console').boundingBox();
  check(commands.y + commands.height < walking.y, 'Mobile Commands stays clear of the movement controls');
  return { checks };
}
