async page => {
  const origin='http://127.0.0.1:5180',checks=[],errors=[];
  page.setDefaultTimeout(45000);
  const check=(condition,label)=>{if(!condition)throw new Error(label);checks.push(label);};
  const ready=async p=>{await p.waitForFunction(()=>window.__riverMultiplayer?.().connected&&document.querySelector('#canvas-host').dataset.playerReady==='true',null,{timeout:60000});};
  page.on('pageerror',error=>errors.push('Alice: '+error.message));
  await page.context().addCookies([{name:'fixture_session',value:'alice',url:origin}]);
  await page.setViewportSize({width:1440,height:1000});
  await page.goto(origin+'/?motion-debug=1');await ready(page);
  const otherContext=await page.context().browser().newContext({viewport:{width:1440,height:1000}});
  await otherContext.addCookies([{name:'fixture_session',value:'bob',url:origin}]);
  const other=await otherContext.newPage();other.setDefaultTimeout(45000);other.on('pageerror',error=>errors.push('Bob: '+error.message));
  try {
    await other.goto(origin+'/?motion-debug=1');await ready(other);
    await page.waitForFunction(()=>window.__riverMultiplayer().remotes?.some(player=>player.id==='bob'&&player.ready),null,{timeout:60000});
    await other.waitForFunction(()=>window.__riverMultiplayer().remotes?.some(player=>player.id==='alice'&&player.ready),null,{timeout:60000});
    await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.unicornsReady==='true'&&document.querySelector('#canvas-host').dataset.carriageDriverReady==='true');
    check(await page.locator('#player-form').count()===0,'Jevica is the only playable form');
    check(await page.evaluate(()=>document.querySelector('.force-controls').hidden&&document.querySelector('#player-carriage').parentElement.hidden&&!window.__riverCarriage().visible),'Unsynchronized carriage and Force controls remain hidden in shared play after assets load');
    check(await page.evaluate(()=>!window.__riverPeople().some(p=>p.id==='carriage-driver')&&!window.__riverMultiplayer().snapshot.locals.some(p=>p.id==='carriage-driver')),'Shared diagnostics and town exclude the solo coachman');
    await page.locator('#canvas-host').focus();await page.keyboard.press('KeyT');
    check(await page.evaluate(()=>!window.__riverForce().enabled),'Force shortcut cannot bypass shared-mode gating');
    check(await page.evaluate(()=>window.__riverMultiplayer().snapshot.players.length===2),'Two accounts share the roster and rendered Jevica avatars');
    await page.bringToFront();
    const openPanel=page.getByRole('button',{name:'Show controls',exact:true});
    if(await openPanel.isVisible())await openPanel.click();
    const target=await page.evaluate(()=>{
      const locals=window.__riverMultiplayer().snapshot.locals.filter(local=>!local.indoor&&!local.wish);
      return locals.sort((a,b)=>locals.filter(p=>Math.hypot(p.position[0]-b.position[0],p.position[1]-b.position[1])<9).length-locals.filter(p=>Math.hypot(p.position[0]-a.position[0],p.position[1]-a.position[1])<9).length)[0].id;
    });
    await page.locator('#community-local').selectOption(target);
    await page.getByRole('button',{name:'Meet a local',exact:true}).click();
    await page.locator('#wish-grant').waitFor({state:'visible'});
    const resident=await page.locator('#community-local').inputValue();
    await page.locator('#wish-choice').selectOption('dragon');await page.locator('#wish-grant').click();
    await page.waitForFunction(()=>document.querySelector('.wish-card').dataset.phase==='gift');
    await other.waitForFunction(id=>window.__riverMultiplayer().snapshot.locals.find(local=>local.id===id)?.wish?.kind==='dragon',resident);
    await page.waitForFunction(()=>document.querySelector('.wish-card')?.getAttribute('aria-busy')==='false');
    check(await page.locator('#wish-undo').evaluate(node=>node===document.activeElement),'Confirmed grant moves keyboard focus to undo');
    check(await other.evaluate(id=>window.__riverMultiplayer().snapshot.locals.find(local=>local.id===id).wish.ownerId==='alice',resident),'Second player sees server-owned dragon wish');
    await page.waitForFunction(()=>document.querySelector('.wish-card').dataset.phase==='trouble',null,{timeout:30000});
    await other.waitForFunction(()=>window.__riverMultiplayer().snapshot.wishes.trouble===1);
    check(await page.evaluate(()=>window.__riverWishes().some(person=>person.wish?.kind==='dragon'&&person.props.includes('Wish dragon'))),'Egg hatches into a visible dragon');
    check(await other.evaluate(()=>window.__riverMultiplayer().snapshot.wishes.affected>0),'The same wish disrupts town residents for both players');
    await page.locator('#wish-undo').click();
    await other.waitForFunction(id=>!window.__riverMultiplayer().snapshot.locals.find(local=>local.id===id).wish,resident);
    await page.waitForFunction(()=>document.querySelector('.wish-card')?.getAttribute('aria-busy')==='false');
    check(await page.locator('#wish-choice').evaluate(node=>node===document.activeElement),'Confirmed undo restores keyboard focus');
    await page.locator('#wish-choice').selectOption('invisibility');await page.locator('#wish-grant').click();
    await page.waitForFunction(()=>document.querySelector('.wish-card').dataset.phase==='trouble',null,{timeout:30000});
    check(await page.evaluate(()=>window.__riverWishes().some(person=>person.wish?.kind==='invisibility'&&person.skin===0&&person.clothes>0)),'Invisible resident keeps visible clothing in shared play');
    await other.reload();await ready(other);
    await other.waitForFunction(id=>window.__riverMultiplayer().snapshot.locals.find(local=>local.id===id)?.wish?.kind==='invisibility',resident);
    check(true,'Reload rejoins the existing town and keeps its active wishes');
    await page.locator('#wish-undo').click();
    await page.waitForFunction(()=>document.querySelector('.wish-card')?.getAttribute('aria-busy')==='false' && !document.querySelector('#wish-choice')?.disabled);
    await page.locator('#wish-choice').press('Escape');
    await page.locator('#community-dialogue').waitFor({state:'hidden'});
    const closePanel=page.getByRole('button',{name:'Hide controls',exact:true});
    if(await closePanel.isVisible())await closePanel.click();
    const before=await page.evaluate(()=>window.__riverMultiplayer().snapshot.players.find(p=>p.id==='alice').position);
    await page.bringToFront();await page.locator('#canvas-host').focus();await page.keyboard.down('KeyS');
    await page.waitForTimeout(1200);await page.keyboard.up('KeyS');
    await other.waitForFunction(({id,before})=>{const p=window.__riverMultiplayer().snapshot.players.find(p=>p.id===id);return Math.hypot(p.position[0]-before[0],p.position[1]-before[1])>0.25;},{id:'alice',before});
    check(true,'Walking is validated and visible to the other player');
    await page.setViewportSize({width:390,height:844});
    check(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),'Shared town has no mobile horizontal overflow');
    await page.screenshot({path:'output/playwright/multiplayer-mobile.png'});
    // Sign out through the same authenticated HTTP + socket lifecycle used by the client.
    await other.bringToFront();
    const showControls=other.getByRole('button',{name:'Show controls',exact:true});
    if(await showControls.isVisible())await showControls.click();
    await other.getByRole('button',{name:'Sign out',exact:true}).click();
    await other.waitForFunction(()=>document.querySelector('.multiplayer-gate')?.hidden===false);
    await page.waitForFunction(()=>window.__riverMultiplayer().snapshot.players.length===1);
    await other.getByRole('link',{name:'Sign in with WorkOS'}).waitFor({state:'visible'});
    check(await other.getByRole('link',{name:'Sign in with WorkOS'}).isVisible(),'Sign-out revokes play and returns to the sign-in gate');
    check(!errors.length,'No uncaught errors: '+errors.join('; '));
    return {passed:true,checks,errors,scope:'Two real browsers, test-only authenticated identities, real shared server; not live WorkOS or production hosting acceptance.'};
  } catch(error) {return {passed:false,checks,errors,failure:error.message};} finally {await otherContext.close();await page.goto('about:blank');}
}
