async page => {
  const checks=[], errors=[];
  const check=(ok,label)=>{if(!ok) throw new Error(label); checks.push(label);};
  page.on('pageerror',error=>errors.push(error.message));
  await page.setViewportSize({width:1440,height:1000});
  await page.goto('http://127.0.0.1:5173/');
  await page.locator('#loading').waitFor({state:'hidden'});
  check(await page.locator('#walking-hud').isVisible(),'Starts on foot');
  check(await page.locator('#overview,#street,#ride,#walk,#flight-hud,#scene-select,#economy-hud').count()===0,'No alternate view or scene controls');
  check(await page.locator('#walking-hud').getAttribute('data-eye-height')==='1.68','Camera remains at human eye height');
  const before=JSON.parse(await page.locator('#walking-hud').getAttribute('data-position'));
  await page.locator('#canvas-host').focus();
  await page.keyboard.down('KeyW'); await page.waitForTimeout(1000); await page.keyboard.up('KeyW');
  const after=JSON.parse(await page.locator('#walking-hud').getAttribute('data-position'));
  check(Math.hypot(after[0]-before[0],after[2]-before[2])>0.5,'Walking advances along the street');
  await page.mouse.wheel(0,-700);
  check(await page.locator('#walking-hud').getAttribute('data-eye-height')==='1.68','Scrolling cannot zoom into an aerial view');
  if(await page.locator('#panel-toggle').getAttribute('aria-expanded')==='false') await page.locator('#panel-toggle').click();
  check(await page.locator('.panel-scroll > section').first().getAttribute('id')==='community-section','People precede shop navigation');
  const first=page.locator('.nearby-person').first();
  await first.focus();
  const focused=await first.getAttribute('id');
  await page.waitForTimeout(650);
  check(await page.evaluate(id=>document.activeElement.id===id,focused),'Nearby card retains keyboard focus across refreshes');
  await page.keyboard.press('Enter');
  check(await page.locator('#community-dialogue').isVisible(),'Keyboard opens nearby conversation');
  await page.locator('#community-about').click();
  await page.waitForFunction(()=>!document.querySelector('#community-attribution').textContent.includes('checking'));
  check((await page.locator('#community-speech').textContent()).length>40,'Conversation answers a topic');
  await page.locator('#community-close').click();
  check(await page.locator('#canvas-host').evaluate(el=>el===document.activeElement),'Closing returns focus to walking');
  await page.keyboard.press('KeyE');
  check(await page.locator('#community-dialogue').isVisible(),'E reopens the nearby encounter');
  await page.locator('#community-close').click();
  if(!await page.locator('#walking-meet-nearby').isVisible())await page.locator('.walking-more summary').click();
  await page.locator('#walking-meet-nearby').click();
  check(await page.locator('#community-dialogue').isVisible(),'Primary Meet someone nearby action opens conversation');
  await page.locator('#community-close').click();
  await page.keyboard.press('Escape');
  check(await page.locator('#walking-hud').isVisible(),'Escape never enters an aerial mode');
  await page.locator('[data-section=explore-section]').click();
  await page.locator('#destination').selectOption({label:'Cartier'});
  await page.locator('#visit-destination').click();
  check(await page.locator('#walking-hud').isVisible(),'Shop arrival stays on foot');
  await page.locator('#reload').click();
  await page.locator('#loading').waitFor({state:'hidden'});
  check(await page.locator('#walking-hud').isVisible(),'Reload stays on foot');
  await page.locator('#panel-toggle').click();
  await page.screenshot({path:'output/playwright/street-level-desktop.png'});
  await page.setViewportSize({width:390,height:844});
  check(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),'Mobile has no horizontal overflow');
  if(!await page.locator('#walking-meet-nearby').isVisible())await page.locator('.walking-more summary').click();
  await page.locator('#walking-meet-nearby').click();
  check(await page.locator('#community-dialogue').isVisible(),'Mobile primary action opens conversation');
  await page.screenshot({path:'output/playwright/street-level-mobile.png'});
  await page.locator('#community-close').click();
  check(errors.length===0,`No page errors: ${errors.join('; ')}`);
  return {passed:checks.length,checks,errors};
}
