async page=>{
  const checks=[],errors=[];const check=(ok,message)=>{if(!ok)throw new Error(message);checks.push(message);};
  page.on('pageerror',error=>errors.push(error.message));
  await page.setViewportSize({width:1440,height:1000});await page.emulateMedia({reducedMotion:'no-preference'});
  await page.goto('http://127.0.0.1:5181/?motion-debug=1');
  await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.playerReady==='true',null,{timeout:90000});
  if(await page.locator('#panel-toggle').getAttribute('aria-expanded')==='false')await page.locator('#panel-toggle').click();
  await page.locator('#rail-tab-0').focus();await page.keyboard.press('ArrowRight');
  check(await page.locator('#rail-tab-1').getAttribute('aria-selected')==='true','Arrow keys select Places and preserve tab focus');
  check(await page.locator('#explore-section').isVisible(),'Places panel remains accessible');
  await page.keyboard.press('ArrowRight');
  check(await page.locator('#rail-tab-2').getAttribute('aria-selected')==='true','Keyboard selects Settings');
  const keyboardMotion=await page.locator('#control-panel').evaluate(e=>getComputedStyle(e).transitionDuration);
  check(keyboardMotion==='0s','Keyboard navigation does not wait on panel animation');
  await page.locator('[data-theme-preference=dark]').click();await page.waitForTimeout(200);
  check(await page.locator('html').getAttribute('data-theme')==='dark','Dark theme switches cleanly');
  check(!await page.locator('html').getAttribute('data-theme-changing'),'Theme transition suppression clears');
  await page.screenshot({path:'output/playwright/ui-polish-dark.png'});
  await page.locator('[data-theme-preference=light]').click();
  await page.locator('#rail-tab-0').click();
  await page.locator('#community-local').selectOption(await page.locator('#community-local option').evaluateAll(options=>options.find(option=>option.value.startsWith('store-')).value));await page.locator('#community-meet').click();
  await page.locator('#community-dialogue').waitFor({state:'visible'});
  check(await page.locator('#community-close').isVisible(),'Conversation opens with a reachable close control');
  await page.locator('#community-about').click();
  await page.waitForTimeout(300);
  check(Boolean(await page.locator('#community-speech').textContent()),'Conversation topics still produce dialogue');
  check(await page.locator('.wish-card').count()>0,'Wishes remain reachable in conversation');
  await page.screenshot({path:'output/playwright/ui-polish-conversation.png'});
  await page.locator('#community-close').click();await page.waitForTimeout(220);
  check(!await page.locator('#community-dialogue').isVisible(),'Conversation exit finishes without an invisible input blocker');
  await page.locator('#panel-toggle').click();await page.waitForTimeout(220);
  check(await page.locator('#control-panel').evaluate(e=>e.inert),'Collapsed controls are inert');
  check(await page.evaluate(()=>document.activeElement.id==='canvas-host'),'Closing the rail returns pointer play to the canvas');
  for(let i=0;i<4;i++)await page.locator('#panel-toggle').click({delay:15});
  await page.waitForTimeout(220);
  check(await page.locator('#panel-toggle').getAttribute('aria-expanded')==='false','Rapid interrupted toggles settle in the requested state');
  check(await page.locator('#control-panel').evaluate(e=>getComputedStyle(e).opacity==='0'),'Rail finishes its exit');
  for(let i=0;i<5;i++) {
    await page.locator('#panel-toggle').click();await page.locator('#rail-tab-0').focus();
    check(await page.evaluate(()=>document.activeElement.id==='rail-tab-0'),`Opening ${i+1}: focus works in the first animation frame`);
    await page.keyboard.press('ArrowRight');
    check(await page.locator('#rail-tab-1').getAttribute('aria-selected')==='true',`Opening ${i+1}: immediate keyboard navigation works`);
    await page.locator('#panel-toggle').click();await page.waitForTimeout(220);
  }
  if(!await page.locator('.player-settings').evaluate(e=>e.open))await page.locator('.player-settings > summary').click();
  await page.locator('#player-camera').click();
  check(await page.evaluate(()=>document.activeElement.id==='canvas-host'),'Pointer camera controls return focus to movement');
  await page.locator('#player-camera').click();
  const b=await page.locator('#player-camera').boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.waitForTimeout(160);
  check(await page.locator('#player-camera').evaluate(e=>Math.abs(Number(getComputedStyle(e).scale)-.96)<.002),'Pointer press feedback reaches the shared restrained scale');
  await page.mouse.up();await page.waitForTimeout(180);
  check(await page.locator('#player-camera').evaluate(e=>['none','1'].includes(getComputedStyle(e).scale)),'Press feedback releases cleanly');
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.locator('#panel-toggle').click();
  const staticUI=await page.evaluate(()=>['#control-panel','#player-camera','#community-dialogue'].map(s=>getComputedStyle(document.querySelector(s)).transitionDuration));
  check(staticUI.every(v=>v==='0s'),'Reduced motion removes UI transitions across the rail, ride controls and dialogue');
  await page.locator('#panel-toggle').click();
  check(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),'Desktop UI has no horizontal overflow');
  check(!errors.length,'No uncaught UI errors');
  return {checks,keyboardMotion,staticUI,errors};
}
