async page => {
  const check=(condition,message)=>{if(!condition)throw new Error(message);};
  const errors=[],packets=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('request',request=>{if(request.url().endsWith('/v1/decisions'))packets.push(request.postDataJSON());});
  const jobs=()=>page.locator('#community-visits').evaluate(el=>JSON.parse(el.dataset.jobs));
  const locals=()=>page.locator('#community-life-status').evaluate(el=>JSON.parse(el.dataset.residents));
  await page.setViewportSize({width:1920,height:1080});
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.goto('http://127.0.0.1:5173/');
  await page.locator('#loading').waitFor({state:'hidden'});
  await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.charactersReady==='24');
  if(await page.locator('#panel-toggle').getAttribute('aria-expanded')==='false')await page.locator('#panel-toggle').click();
  await page.locator('#community-run').click();
  await page.locator('#community-local').selectOption('local-00');await page.locator('#community-meet').click();
  await page.locator('#community-ask').click();await page.locator('#community-dispatch').click();
  await page.waitForFunction(()=>JSON.parse(document.querySelector('#community-visits').dataset.jobs).some(job=>job.phase==='traveling'));
  const visit=(await jobs())[0],helperId=visit.helperId;
  check(helperId && helperId!=='local-00','A different existing resident must volunteer');
  check((await page.locator('#community-resources').textContent()).includes('3 volunteer visits left'),'Dispatch must reserve exactly one visit');
  await page.locator('#community-visits button').click();
  check(await page.locator('#community-dialogue').isHidden(),'Finding the volunteer must leave them free to work');
  check(await page.locator('#canvas-host').evaluate(el=>el===document.activeElement),'Finding a volunteer must restore walking input');
  await page.waitForFunction(()=>Number(document.querySelector('#canvas-host').dataset.volunteerKits)>0);
  await page.screenshot({path:'output/playwright/volunteer-travel.png'});
  await page.locator('#community-local').selectOption(helperId);await page.locator('#community-meet').click();
  const taskDialogue=await page.locator('#community-speech').textContent();
  check(taskDialogue.includes('Maya') && taskDialogue.includes('cooling supplies'),'The helper must describe their current assignment');
  await page.waitForTimeout(250);const chatting=(await locals()).find(local=>local.id===helperId).position;
  await page.waitForTimeout(600);
  check(JSON.stringify((await locals()).find(local=>local.id===helperId).position)===JSON.stringify(chatting),'Talking to the helper must hold their route');
  await page.locator('#community-close').click();
  await page.locator('#community-run').click();await page.waitForTimeout(250);
  const paused=(await locals()).find(local=>local.id===helperId),progress=(await jobs())[0].progress;
  await page.waitForTimeout(1200);
  check(JSON.stringify((await locals()).find(local=>local.id===helperId).position)===JSON.stringify(paused.position),'Scenario pause must stop the helper');
  check((await jobs())[0].progress===progress,'Paused work cannot complete');
  await page.getByText('Adjust the economy',{exact:true}).click();await page.locator('#economy-storm').check();
  await page.locator('#community-run').click();
  await page.waitForFunction(()=>JSON.parse(document.querySelector('#community-visits').dataset.jobs)[0]?.phase==='storm_hold');
  await page.waitForTimeout(1400);check((await jobs())[0].progress===progress,'Storms must hold work before the economic run is enabled');
  await page.locator('#economy-storm').uncheck();
  await page.waitForFunction(()=>JSON.parse(document.querySelector('#community-visits').dataset.jobs).some(job=>job.phase==='assisting'),null,{timeout:80000});
  const atArrival=await locals(),helper=atArrival.find(local=>local.id===helperId),recipient=atArrival.find(local=>local.id==='local-00');
  const separation=Math.hypot(helper.position[0]-recipient.position[0],helper.position[1]-recipient.position[1]);
  check(separation<=1.5,'On-site work must require physical arrival');
  check(helper.distance>15,'Helper must have traveled through the district');
  await page.locator('#community-visits button').click();
  await page.screenshot({path:'output/playwright/volunteer-arrival.png'});
  await page.waitForFunction(()=>document.querySelector('#community-progress').textContent.startsWith('1 / 6'),null,{timeout:15000});
  check((await jobs()).length===0,'Completed visit must leave the active queue');
  check(packets.some(packet=>packet.agents.length===1 && packet.agents[0].id===helperId && packet.agents[0].activity.includes('volunteering')),'Paused ambient walks must still send a bounded helper reaction packet');
  await page.locator('#community-run').click();
  await page.locator('#community-local').selectOption('local-00');await page.locator('#community-meet').click();
  check((await page.locator('.community-need-label').textContent()).includes('request resolved'),'Recipient must report a completed outcome');
  await page.screenshot({path:'output/playwright/volunteer-outcome.png'});
  await page.locator('#community-close').click();await page.locator('#community-reset').click();
  await page.waitForTimeout(250);check((await locals()).every(local=>!local.visitId),'Reset must release volunteer assignments');
  await page.emulateMedia({reducedMotion:'no-preference'});
  check(errors.length===0,`Browser errors: ${errors.join('; ')}`);
  return {helperId,cast:atArrival.length,walkedMeters:helper.distance,arrivalSeparationMeters:separation,physicalArrival:true,pause:true,stormHold:true,ambientPauseKeepsVisits:true,visibleSupplyBag:true,taskAwareDialogue:true,conversationHoldsVisit:true,needsResolved:true,resetReleasesHelper:true,browserErrors:errors};
}
