import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import Redis from 'ioredis';
import { WebSocket } from 'ws';
import { createWorldGateway } from '../world-gateway.js';
import { createRedisRoom } from '../redis-room.js';
import { createRedisSecurity } from '../redis-security.js';
import { JEVICA_ADMIN_USER_IDS } from '../admin.js';
import { roomPrefixFor } from '../world-keys.js';
import { approvedWaitlist } from './waitlist-fixture.js';

test('Jevica publishes a second world that survives gateway replacement', {skip:!process.env.REDIS_URL,timeout:60_000},async t=>{
  const redis=new Redis(process.env.REDIS_URL);redis.on('error',()=>{});
  const namespace=`river-oaks:gateway-test:${randomUUID()}`,prefix=`{${namespace}}`,origin='https://sim.jev.works';
  const worldData=JSON.parse(await readFile(new URL('../../preview/public/data/district.json',import.meta.url)));
  const region=JSON.parse(await readFile(new URL('../../preview/public/data/sample-region.json',import.meta.url)));
  const admin=JEVICA_ADMIN_USER_IDS[0],users=new Map([['admin',admin],['guest','guest-user']]);
  const auth={handle:async()=>false,authenticate:async req=>{
    const userId=users.get(req.headers.cookie?.match(/test_session=(\w+)/)?.[1]);
    return userId?{userId,name:userId,sessionId:userId+'-session',csrfToken:'test-csrf',expiresAt:Date.now()+60_000}:null;
  },isSessionActive:async()=>true,close(){}};
  const security=createRedisSecurity({redis,prefix});
  const createGateway=()=>createWorldGateway({redis,namespace,worldData,auth,security,waitlist:approvedWaitlist,origin,moderators:[admin]});
  let gateway=createGateway();
  await new Promise(resolve=>gateway.server.listen(0,'127.0.0.1',resolve));
  let base=`http://127.0.0.1:${gateway.server.address().port}`;const sockets=[];
  t.after(async()=>{
    for(const socket of sockets)socket.terminate();
    await gateway.close();security.close();
    const keys=await redis.keys(`*${namespace}*`);if(keys.length)await redis.del(...keys);
    await redis.quit();
  });
  const post=(user,path,data)=>fetch(base+path,{method:'POST',headers:{Origin:origin,Cookie:`test_session=${user}`,'X-CSRF-Token':'test-csrf','Content-Type':'application/json'},body:JSON.stringify(data)});
  const proposal={id:'moon-garden',title:'Moon Garden',description:'A quiet place to meet.',region};
  assert.equal((await post('guest','/api/worlds',proposal)).status,403);
  assert.equal((await post('admin','/api/worlds',{...proposal,title:'Unauthorized shape',ownerId:'guest'})).status,400);
  const published=await post('admin','/api/worlds',proposal);
  assert.equal(published.status,201);
  assert.equal((await published.json()).world.ownerId,admin);
  const editable=await (await post('admin','/api/world-draft/load',{id:'moon-garden'})).json();
  const changed={...editable.publishedRegion,places:editable.publishedRegion.places.map((place,index)=>index?place:{...place,name:'Hidden revision'})};
  assert.equal((await post('guest','/api/world-draft/load',{id:'moon-garden'})).status,403);
  assert.equal((await post('admin','/api/world-draft/save',{id:'moon-garden',baseRegionSha256:editable.world.regionSha256,expectedDraftVersion:0,region:changed})).status,200);
  assert.deepEqual((await (await fetch(base+'/api/worlds')).json()).worlds.map(world=>world.id),['river-oaks','moon-garden']);
  assert.deepEqual((await (await fetch(base+'/api/worlds')).json()).worlds.map(world=>world.visitors),[0,0]);
  const publishedData=await (await fetch(base+'/api/world-data?world=moon-garden',{headers:{Cookie:'test_session=admin'}})).json();
  assert.equal(publishedData.template,'region-v1');
  assert.equal(publishedData.world.buildings.length,4);
  assert.equal((await fetch(base+'/api/world-data?world=missing-world',{headers:{Cookie:'test_session=admin'}})).status,404);
  assert.equal((await fetch(base+'/api/world-data?world=moon-garden&world=river-oaks',{headers:{Cookie:'test_session=admin'}})).status,400);
  assert.equal((await post('admin','/api/multiplayer/ticket?world=missing-world',{})).status,404);
  const open=async(worldId,user='admin')=>{
    const ticketResponse=await post(user,`/api/multiplayer/ticket?world=${worldId}`,{});
    assert.equal(ticketResponse.status,200);
    const ticket=(await ticketResponse.json()).ticket;
    const socket=new WebSocket(`${base.replace('http:','ws:')}/multiplayer?world=${worldId}&protocol=2&ticket=${ticket}`,{headers:{Origin:origin,Cookie:`test_session=${user}`}});
    sockets.push(socket);
    const snapshot=await new Promise((resolve,reject)=>{
      socket.once('error',reject);
      socket.on('message',raw=>{const value=JSON.parse(raw);if(value.type==='snapshot')resolve(value);});
    });
    return {socket,snapshot};
  };
  const first=await open('river-oaks'),second=await open('moon-garden');
  assert.equal(first.snapshot.worldId,'river-oaks');
  assert.equal(second.snapshot.worldId,'moon-garden');
  assert.equal(second.snapshot.locals.length,8);
  assert.equal(first.snapshot.locals.length>8,true);
  assert.equal(first.snapshot.players.length,1);
  assert.equal(second.snapshot.players.length,1);
  const riverMark=await (await post('admin','/api/landmarks/add?world=river-oaks',{name:'District arrival'})).json();
  const moonMark=await (await post('admin','/api/landmarks/add?world=moon-garden',{name:'Garden arrival'})).json();
  assert.equal(riverMark.landmark.worldId,'river-oaks');
  assert.equal(moonMark.landmark.worldId,'moon-garden');
  assert.deepEqual((await (await post('admin','/api/landmarks/list?world=river-oaks',{})).json()).landmarks.map(item=>item.worldId),['river-oaks']);
  assert.deepEqual((await (await post('admin','/api/landmarks/list?world=river-oaks&allWorlds=1',{})).json()).landmarks.map(item=>item.worldId).sort(),['moon-garden','river-oaks']);
  assert.deepEqual((await (await post('admin','/api/landmarks/list?world=moon-garden&allWorlds=1',{})).json()).landmarks.map(item=>item.id).sort(),[riverMark.landmark.id,moonMark.landmark.id].sort());
  assert.deepEqual((await (await post('guest','/api/landmarks/list?world=moon-garden',{})).json()).landmarks,[]);
  assert.equal((await (await post('guest','/api/landmarks/remove?world=river-oaks',{id:moonMark.landmark.id,worldId:'moon-garden'})).json()).removed,false);
  assert.equal((await (await post('admin','/api/landmarks/remove?world=river-oaks',{id:moonMark.landmark.id,worldId:'missing-world'})).json()).removed,false);
  const command=(socket,requestId,body)=>new Promise((resolve,reject)=>{
    const receive=raw=>{const value=JSON.parse(raw);if(value.type==='result'&&value.requestId===requestId){socket.off('message',receive);resolve(value);}};
    socket.on('message',receive);socket.once('error',reject);socket.send(JSON.stringify({requestId,...body}));
  });
  assert.equal((await command(second.socket,'look',{type:'appearance',appearance:'woman-casual'})).ok,true);
  assert.equal((await command(second.socket,'gait',{type:'movement',movement:'beast'})).ok,true);
  const riverRoom=(await gateway.worldFor('river-oaks')).room;
  const riverConnection=(await riverRoom.read()).connections.find(connection=>connection.userId===admin);
  assert.equal((await riverRoom.request({type:'heartbeat',userId:admin,connectionId:riverConnection.connectionId})).ok,true);
  assert.equal((await riverRoom.read()).snapshot.players.find(player=>player.id===admin).appearance,'woman-casual');
  assert.equal((await riverRoom.read()).snapshot.players.find(player=>player.id===admin).movement,'beast');
  const sameAccountOtherWorld=await open('river-oaks');
  assert.equal(sameAccountOtherWorld.snapshot.players.find(player=>player.id===admin).appearance,'woman-casual');
  assert.equal(sameAccountOtherWorld.snapshot.players.find(player=>player.id===admin).movement,'beast');
  assert.equal((await command(sameAccountOtherWorld.socket,'human',{type:'appearance',appearance:'sable-human'})).ok,true);
  const moonRoom=(await gateway.worldFor('moon-garden')).room;
  const moonConnection=(await moonRoom.read()).connections.find(connection=>connection.userId===admin);
  assert.equal((await moonRoom.request({type:'heartbeat',userId:admin,connectionId:moonConnection.connectionId})).ok,true);
  assert.equal((await moonRoom.read()).snapshot.players.find(player=>player.id===admin).appearance,'sable-human');
  assert.equal((await moonRoom.read()).snapshot.players.find(player=>player.id===admin).movement,'upright');
  assert.deepEqual((await (await fetch(base+'/api/worlds')).json()).worlds.map(world=>world.visitors),[1,1]);
  assert.equal((await gateway.worldFor('moon-garden')).room.worldId,'moon-garden');
  assert.equal((await gateway.worldFor('missing-world')),null);
  for(const socket of sockets)socket.terminate();
  await gateway.close();
  gateway=createGateway();
  await new Promise(resolve=>gateway.server.listen(0,'127.0.0.1',resolve));
  base=`http://127.0.0.1:${gateway.server.address().port}`;
  assert.deepEqual((await (await fetch(base+'/api/worlds')).json()).worlds.map(world=>world.id),['river-oaks','moon-garden']);
  const adminAgain=await open('moon-garden');
  assert.equal(adminAgain.snapshot.worldId,'moon-garden');
  assert.deepEqual((await (await post('admin','/api/landmarks/list?world=moon-garden&allWorlds=1',{})).json()).landmarks.map(item=>item.id).sort(),[riverMark.landmark.id,moonMark.landmark.id].sort());
  assert.equal((await (await post('admin','/api/landmarks/remove?world=moon-garden',{id:riverMark.landmark.id,worldId:'river-oaks'})).json()).removed,true);
  assert.deepEqual((await (await post('admin','/api/landmarks/list?world=river-oaks&allWorlds=1',{})).json()).landmarks.map(item=>item.id),[moonMark.landmark.id]);
  assert.equal(adminAgain.snapshot.players.find(player=>player.id===admin).appearance,'sable-human');
  assert.equal(adminAgain.snapshot.players.find(player=>player.id===admin).movement,'upright');
  assert.equal((await (await post('admin','/api/world-draft/load',{id:'moon-garden'})).json()).draft.region.places[0].name,'Hidden revision');
  assert.notEqual((await (await fetch(base+'/api/world-data?world=moon-garden',{headers:{Cookie:'test_session=admin'}})).json()).world.communityLocations[0].name,'Hidden revision');
  assert.equal((await (await fetch(base+'/api/world-data?world=moon-garden',{headers:{Cookie:'test_session=admin'}})).json()).world.provenance.kind,'creator');
  const visitor=await open('moon-garden','guest');
  const visitorsAfterRestart=(await (await fetch(base+'/api/worlds')).json()).worlds;
  assert.equal(visitorsAfterRestart.find(world=>world.id==='moon-garden').visitors,2);
  assert.equal(visitorsAfterRestart.some(world=>Object.hasOwn(world,'connections')||Object.hasOwn(world,'players')),false);
  const visitorInRiver=await open('river-oaks','guest');
  assert.equal(visitor.snapshot.players.some(player=>player.id==='guest-user'),true);
  assert.equal((await post('guest','/api/social/request?world=moon-garden',{peerId:admin})).status,200);
  const pendingContacts=(await (await post('guest','/api/social/list?world=moon-garden',{})).json()).contacts;
  assert.equal(Object.hasOwn(pendingContacts[0],'presence'),false);
  assert.equal((await post('admin','/api/social/accept?world=river-oaks',{peerId:'guest-user'})).status,200);
  const adminContacts=(await (await post('admin','/api/social/list?world=river-oaks',{})).json()).contacts;
  const guestContacts=(await (await post('guest','/api/social/list?world=moon-garden',{})).json()).contacts;
  assert.deepEqual(adminContacts[0].presence,{worldId:'river-oaks',title:'River Oaks District'});
  assert.deepEqual(guestContacts[0].presence,{worldId:'moon-garden',title:'Moon Garden'});
  assert.equal((await post('guest','/api/social/send?world=moon-garden',{peerId:admin,text:'See you in River Oaks'})).status,200);
  const crossWorldMessages=await (await post('admin','/api/social/messages?world=river-oaks',{peerId:'guest-user'})).json();
  assert.equal(crossWorldMessages.messages[0].text,'See you in River Oaks');
  const closed=Promise.all([visitor,visitorInRiver].map(({socket})=>new Promise(resolve=>socket.once('close',resolve))));
  assert.equal((await post('admin','/api/moderation/ban',{userId:'guest-user',banned:true})).status,200);
  await closed;
  assert.equal((await post('guest','/api/multiplayer/ticket?world=moon-garden',{})).status,403);
  const oldHash=(await (await fetch(base+'/api/world-data?world=moon-garden',{headers:{Cookie:'test_session=admin'}})).json()).regionSha256;
  const revisionClosed=new Promise(resolve=>adminAgain.socket.once('close',resolve));
  assert.equal((await post('guest','/api/world-draft/apply',{id:'moon-garden',expectedDraftVersion:1})).status,403);
  const applied=await post('admin','/api/world-draft/apply',{id:'moon-garden',expectedDraftVersion:1});
  assert.equal(applied.status,200);
  assert.equal((await applied.json()).world.revision,2);
  assert.equal(await revisionClosed,4000);
  const live=await (await fetch(base+'/api/world-data?world=moon-garden',{headers:{Cookie:'test_session=admin'}})).json();
  assert.notEqual(live.regionSha256,oldHash);
  assert.equal(live.world.communityLocations[0].name,'Hidden revision');
  assert.equal((await open('moon-garden')).snapshot.regionSha256,live.regionSha256);
  assert.equal((await post('admin','/api/world-draft/apply',{id:'moon-garden',expectedDraftVersion:1})).status,409);
  assert.equal((await post('guest','/api/world-draft/history',{id:'moon-garden'})).status,403);
  assert.equal((await post('guest','/api/world-draft/version',{id:'moon-garden',revision:1,baseRegionSha256:live.regionSha256})).status,403);
  const history=await (await post('admin','/api/world-draft/history',{id:'moon-garden'})).json();
  assert.deepEqual(history.versions.map(version=>version.revision),[1]);
  assert.equal((await post('admin','/api/world-draft/version',{id:'moon-garden',revision:0,baseRegionSha256:live.regionSha256})).status,400);
  assert.equal((await post('admin','/api/world-draft/version',{id:'moon-garden',revision:1,baseRegionSha256:oldHash})).status,409);
  const original=await (await post('admin','/api/world-draft/version',{id:'moon-garden',revision:1,baseRegionSha256:live.regionSha256})).json();
  assert.equal(original.region.places[0].name,editable.publishedRegion.places[0].name);
  await gateway.close();
  const staleRoom=createRedisRoom({redis,prefix:roomPrefixFor(namespace,'moon-garden'),worldId:'moon-garden',
    worldData:publishedData.world,regionSha256:oldHash,regionCatalog:gateway.catalog,
    authorize:async()=>true,isAdmin:id=>id===admin});
  assert.equal((await staleRoom.tick()).snapshot.regionSha256,live.regionSha256);
  await staleRoom.close();
  gateway=createGateway();
  await new Promise(resolve=>gateway.server.listen(0,'127.0.0.1',resolve));
  base=`http://127.0.0.1:${gateway.server.address().port}`;
  assert.equal((await open('moon-garden')).snapshot.regionSha256,live.regionSha256);
  assert.equal((await post('admin','/api/world-draft/save',{id:'moon-garden',baseRegionSha256:live.regionSha256,expectedDraftVersion:0,region:original.region})).status,200);
  const restored=await post('admin','/api/world-draft/apply',{id:'moon-garden',expectedDraftVersion:1});
  assert.equal(restored.status,200);
  assert.equal((await restored.json()).world.revision,3);
  assert.equal((await (await fetch(base+'/api/world-data?world=moon-garden',{headers:{Cookie:'test_session=admin'}})).json()).world.communityLocations[0].name,editable.publishedRegion.places[0].name);
  assert.deepEqual((await (await post('admin','/api/world-draft/history',{id:'moon-garden'})).json()).versions.map(version=>version.revision),[2,1]);
});
